# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/reduxion
  docker:
    - image: circleci/node:lts-stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/reduxion
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/reduxion
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/reduxion/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
